name: user_painting_tools
description: "This application is for user from user painting tools application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  get: ^4.6.6
  google_fonts: ^6.2.1
  firebase_core: 3.6.0
  cloud_firestore: 5.4.4
  simple_logger: ^1.9.0+3
  provider: ^6.1.2
  firebase_auth: ^5.3.1
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  persistent_bottom_nav_bar: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
