// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPXI_YFd3k1T37RKiBmds6XZJdlLbPUCw',
    appId: '1:1010189134317:web:a1e8c946d1b31a80f39fe4',
    messagingSenderId: '1010189134317',
    projectId: 'painting-tools-aeac4',
    authDomain: 'painting-tools-aeac4.firebaseapp.com',
    storageBucket: 'painting-tools-aeac4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUbc0lynok_VTJUxYhSr44hEG5WrmRqB0',
    appId: '1:1010189134317:android:50479679bce083bff39fe4',
    messagingSenderId: '1010189134317',
    projectId: 'painting-tools-aeac4',
    storageBucket: 'painting-tools-aeac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATXJ5AyYlhTMvpo8XQJ5RxHLZ0UuuCY6s',
    appId: '1:1010189134317:ios:3ecb4dd45b838000f39fe4',
    messagingSenderId: '1010189134317',
    projectId: 'painting-tools-aeac4',
    storageBucket: 'painting-tools-aeac4.appspot.com',
    iosBundleId: 'com.paintingtools.usertools.userPaintingTools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATXJ5AyYlhTMvpo8XQJ5RxHLZ0UuuCY6s',
    appId: '1:1010189134317:ios:3ecb4dd45b838000f39fe4',
    messagingSenderId: '1010189134317',
    projectId: 'painting-tools-aeac4',
    storageBucket: 'painting-tools-aeac4.appspot.com',
    iosBundleId: 'com.paintingtools.usertools.userPaintingTools',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPXI_YFd3k1T37RKiBmds6XZJdlLbPUCw',
    appId: '1:1010189134317:web:17d118ee1415d84ef39fe4',
    messagingSenderId: '1010189134317',
    projectId: 'painting-tools-aeac4',
    authDomain: 'painting-tools-aeac4.firebaseapp.com',
    storageBucket: 'painting-tools-aeac4.appspot.com',
  );
}
